# Generated by Django 3.2.9 on 2021-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_age', models.CharField(max_length=10)),
                ('emp_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
